### ISSUE TITLE
7zip dependency

### ISSUE THREAD

**Issue by Marqin** [patsytau/ce_tools#1]
Is there some reason why external 7zip is used and not Python's built-in `shutil.make_archive` or `zipfile.ZipFile`? Does `.pak` have to be uncompressed (`-mx0` switch)?

**Comment by patsytau** [comment]
Hiya - sorry about the rather extreme delay in responding!

I used 7-zip as in my experience it's proved significantly faster than shutil.make_archive.

If you have a different experience I'd be happy to re-test and update as appropriate.

**Comment by patsytau** [comment]
As of https://github.com/patsytau/ce_tools/commit/123d057205920ea1f9c786ec9971ba69b88a3f2a, 7-zip is not required: if it is not detected, shutil.make_archive is used instead.
